###-ACCOUNT
PUT http://localhost:8081/account/ 
content-type: application/json

{
  "name": "lima"
}

###-ACCOUNT-BY-ID
GET http://localhost:8081/account/29d33a3b-0a5e-4a3a-b0b4-a80ede5afa30
content-type: application/json

###-WALLET
PUT http://localhost:8081/wallet/
content-type: application/json
x-tenant: 2427855323f744bda5e33702c2d05ac2

{
  "name": "john",
  "accountId": "21fce483-6dd6-429b-86d6-8addfe85cfac"
}

###-WALLET-BY-ID
GET http://localhost:8081/wallet/36289c8a-0d57-4cd0-ab3c-9005b82cc2d1 
content-type: application/json

###-CATEGORIES
PUT http://localhost:8081/categories/
content-type: application/json
x-tenant: ce2afbb9572849a7abcc8e5778b218d3

{
  "name": "eletric"
}



###-CATEGORIES-FIND-PAGE
GET http://localhost:8081/categories/page?name=e
content-type: application/json
x-tenant: ce2afbb9572849a7abcc8e5778b218d3



