spring:
  application.name: Financial
  datasource:
    url: jdbc:postgresql://localhost:5432/financial
    username: financial
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true