spring:
  application.name: Financial
  datasource:
    url: jdbc:postgresql://localhost:5432/financial
    username: financial
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    auto-create-topics: false
    pool-timeout: 1_000
    bootstrap-servers: localhost:9092
    producers:
      account:
        topic: account.created