kafka:
  auto-create-topics: true
  pool-timeout: 1_000
  bootstrap-servers: localhost:9092
  producers:
    account:
      topic: account.created
  consumers:
    tenant:
      auto-offset-reset: earliest
      concurrency: 1
      id: kafka-listener-tenant
      topics: ${kafka.producers.account.topic}
      group-id: tenant-service
      max-attempts: 3

spring:
  application.name: Financial
  datasource:
    url: jdbc:postgresql://localhost:5432/financial
    username: financial
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server.port: 8081