CREATE TABLE public.tenant (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    account_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tenant_account FOREIGN KEY (account_id) REFERENCES public.account(id)
);